### ISSUE TITLE
Error:  undefined method `tags' for #<Jekyll::Document:0x007f9cebd76128>

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-archives#50]
I’m experimenting with the very latest builds of both Jekyll (hours before the full release of 3.0.0) and this plugin. I note that in https://github.com/jekyll/jekyll/pull/4055, @parkr mentions that:

> In an effort to not break sites, this is all backwards compatible liquid-wise. The only big difference is that site.posts is a Collection instead of an Array. But I feel more comfortable breaking plugins than I do breaking people's Liquid.

Is this plugin (and the build that supports Jekyll 3) effected by this change? Here is the full trace:

```
JEKYLL_ENV=development bundle exec jekyll build --config config/jekyll.yml,config/jekyll/development.yml --full-rebuild --trace
Configuration file: config/jekyll.yml
Configuration file: config/jekyll/development.yml
            Source: ./source
       Destination: ./public
 Incremental build: disabled
      Generating... 
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:134:in `block in post_attr_hash': undefined method `tags' for #<Jekyll::Document:0x007faf142e12b8> (NoMethodError)
	from (eval):3:in `each'
	from (eval):3:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:134:in `post_attr_hash'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:140:in `tags'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:67:in `read_tags'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:60:in `read'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:47:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/site.rb:154:in `block in generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/site.rb:153:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/site.rb:153:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/site.rb:58:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/command.rb:28:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-74734d46f8f6/bin/jekyll:17:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
rake aborted!
Command failed with status (1): [JEKYLL_ENV=development bundle exec jekyll ...]
/Users/paulrobertlloyd/Sites/paulrobertlloyd.com/Rakefile:28:in `block in <top (required)>'
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build-dev
(See full trace by running task with --trace)
```

**Comment by parkr** [comment]
`document.data['tags']` instead of `document.tags` now.

**Comment by parkr** [comment]
I could do a `method_missing` and `respond_to?` patch for properties in `data`. I thought about it but it freaked me out too much.

**Comment by envygeeks** [comment]
Given we had no deprecation period we should do something to ease the pain, I agree with @parkr it's total craziness to use method_missing but we might have to just so we can trigger a deprecation warning.

**Comment by paulrobertlloyd** [comment]
@parkr Is this a change in Liquid, or in the plugin source? I’m using `site.tags`, but when I remove all tag related Liquid and configuration, the build still fails. Which leads me to think something needs to be updated within the plugin.

**Comment by parkr** [comment]
@paulrobertlloyd It's because instead of a `Post`, you get a `Document` in the latest master.

@envygeeks https://github.com/jekyll/jekyll/pull/4058

**Comment by paulrobertlloyd** [comment]
I’m still confused sorry, where do I need to make this change?

**Comment by parkr** [comment]
> I’m still confused sorry, where do I need to make this change?

@paulrobertlloyd We fixed it in https://github.com/jekyll/jekyll/pull/4058 but in this plugin, `post.tags` is now `post.data['tags']` and `post.categories` is `post.data['categories']`.

**Comment by paulrobertlloyd** [comment]
@parkr Great that it now doesn’t block the build, but still trying to figure out what lines to change to clear the deprecation warning. I’d love to make submit a PR for this fix, if only I knew what to change!

I can’t find reference to post.tags in jekyll-archives.rb; or anything lines pointed to in the error message that looks amenable.

And if you do mean changes to Liquid markup, that doesn’t help either. For reference, here are a few items of (simplified) mark-up I’m using below:

```
{% if page.tags %}
<h1>Tags</h1>
<ul>
    {% for tag in page.tags %}
    <li><a rel="tag" href="/tags/{{ tag | slugify }}">{{ tag }}</a></li>
    {% endfor %}
</ul>
{% endif %}
```

That’s the only place I’m querying tags on a single post/page. Everywhere else, I’m querying `site.tags`, i.e.:

```
<ul>
{% assign tags = site.tags | sort %}
{% for tag_array in tags %}
    {% capture tag %}{{ tag_array[0] }}{% endcapture %}
    <li class="c-list__item"><a rel="tag" href="/tags/{{ tag | slugify }}">{{ tag }}</a></li>
{% endfor %}
</ul>
```

Finally, in my archive template, which tag archives use, I use something like this:

```
{% for item in page.posts %}
    {% include summary.html %} 
{% endfor %}
```

Changing `page.tags` to `page.data.tags`, or `site.tags` to `site.data.tags` makes no difference, the build still fails (or I get the deprecation warning). Feeling a bit thick here… am I missing something obvious?

**Comment by parkr** [comment]
The problem is in the Ruby, not in the Liquid. Check out `lib/jekyll-archives.rb:134`.

**Comment by paulrobertlloyd** [comment]
Okay, so some progress. On line 134 I made the following change:

```diff
- @posts.each { |p| p.send(post_attr.to_sym).each { |t| hash[t] << p } }
+ @posts.each { |p| p.data[post_attr].each { |t| hash[t] << p } }
```

I did this by basically looking at this diff: https://github.com/jekyll/jekyll/commit/e58d0ae0efc23c5d58d16de0758de4f8f6f7d58a#diff-30570eaa19766a40dfa44810430d5e16L222

That seemed to fix the noisiest error. But I still have the following:

```
Deprecation: Collection#each should be called on the #docs array directly.
    Called by /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:134:in `post_attr_hash'.
Deprecation: Collection#each should be called on the #docs array directly.
    Called by /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-archives-c9eac2c729bb/lib/jekyll-archives.rb:150:in `years'.
```

And can’t find any corresponding changes in your Jekyll changes — well, not without reimplementing collections (by which I mean copy and pasting all the collections related code) within this plugin! I don’t think that’s the right answer.

It’s dawning on me that I have no idea what I’m doing! 😭

**Comment by parkr** [comment]
@paulrobertlloyd Is `@posts` a `Collection` or an `Array`? If it's a `Collection`, it's asking you to do `@posts.docs.each` in that line. Not sure what line 150 is.

**Comment by paulrobertlloyd** [comment]
@parkr Okay, great! I’ve figured out the changes that need to be made: https://github.com/paulrobertlloyd/jekyll-archives/commit/fc4f0e0eeca0c7dc9a5e5ffc4e05372c374628cd

Will make a PR shortly… now reviewing the other things that have broken with the latest build of Jekyll 3! 🤔

**Comment by alfredxing** [comment]
@paulrobertlloyd Can you confirm that this is fixed with merge of #53? Thanks!

**Comment by paulrobertlloyd** [comment]
@alfredxing Yes, it does work, thanks for shipping!

However, one downside of testing by version rather than feature, is that the beta releases of 3.0.0 worked differently than the final release: I'm assuming `>=` treats 3.0.0.pre.beta10 the same as 3.0.0?

As 3.0.0 final is breaking my build, I’ve been using beta10, before the collection changes were made. I think I’m going to have to keep this gem locked at specific version/commit for the time being.

**Comment by alfredxing** [comment]
Hm, I did find that, though I assumed that anyone using the betas wouldn't have issues with the final...
I guess locking in the version would be the best idea until 3.0.0 works for you :disappointed:.
